[package]
name = "contor"
version = "0.1.0"
authors = ["Ian Purton <ian.purton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.4"
dotenv = "0.15"
actix-identity = "0.3"
env_logger = "0.7"
regex = "1" # For checking if we need to skip auth

# Used by the proxy
url = "2.0"

# HTML and Validation
markup = "0.11"
validator = { version = "0.12", features = ["derive"] }

bcrypt = "0.9.0"

# Use this for access to hcaptcha
reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls"] }

# The database
sqlx = { version = "0.4", features = [ "runtime-tokio-rustls", "postgres" ] }
serde = "1"

# Use by authentication
futures = "0.3"
serde_json = "1.0" # we store users cookie as json

[build-dependencies]
sha1 = "0.6"  # Use by build.rs for cache busting.

[dev-dependencies]
thirtyfour = "0.23.0" # WebDriver Library for UI testing.
tokio = "0" # Neede by thirtyfour
actix-rt = "2"